### ISSUE TITLE
Migrate to Central Sonatype Repo

### ISSUE THREAD

**Issue by robertjamison** [xxfast/KStore#150]
OSSRH is shutting down [June 30th.](https://central.sonatype.org/news/20250326_ossrh_sunset/) 

Notice from [Sonatype's documentation](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/):

> Migration Required
> If you are currently publishing via OSSRH, you will have to migrate to the Central Publisher Portal in order to utilize this service.

the Gradle built-in maven-publish plugin might be configured as

```kotlin
// ...
    repositories {
        maven {
            name = "ossrh-staging-api"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
        }
    }
// ...
```
For some reason, Sonatype forces you to use their [manual endpoint service](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#manual-api-endpoints) too.

EDIT: I haven't figured out how to push a repo to Central yet.  I'm hoping to copy your technique if you figure it out first.

**Comment by robertjamison** [comment]
Hi @xxfast!

I took the liberty of sending [a pull request for the `build.gradle.kts` file](https://github.com/xxfast/KStore/pull/153) to prepare for migration.  One of the first things we learned is that the `maven-publishing` and `signing` plugins are not compatible with Central Sonatype.  We ended up using Vanniktech, which depends on environmental variables instead of reading values from Gradle files.

Here's what our `publish.yaml` file updated to when we finished:
```yaml
      - name: Publish to MavenCentral
        if: ${{ github.event_name != 'pull_request' }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
```

Let me know if you need help with the migration, as I'll be working on it tomorrow too.
